### ISSUE TITLE
Soil ID Screen: Design Soil Cracks Module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#980] opened 2024-07-31 17:51 UTC
Create a module on the Soil ID screen to display Soil Cracks, which is relevant for the Soil ID algorithm. See parent issue for details. 

## Design
[Updates to Soil ID observation modules](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10962-8287&t=fcyACT7ReWehB7l3-1) Figma

## Acceptance Criteria
- [x] As a user looking at a site's soil ID, I should see user-generated observations on soil cracking, so I can see the information that is relevant for the Soil ID algorithm
- [x] As a user looking at a site's soil ID, I should see a call to action to submit soil cracks information if there are are not observations yet provided.

**Comment by CourtneyLee333** [comment] 2024-10-30 18:41
@DerekCaelin this appears to be a duplicate of https://github.com/techmatters/terraso-product/issues/1085

**Comment by DerekCaelin** [comment] 2024-10-30 20:57
@CourtneyLee333 This issue is about updating the Soil ID screen with a soil cracks module, since soil cracks are relevant for the algorithm. #1085 is for the soil cracks screen itself.

**Closed** 2024-11-21 17:58 UTC
Labels: enhancement, Design
