### ISSUE TITLE
Managing a site

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#95] opened 2023-04-28 14:22 UTC
## User story

- As an authenticated site Manager, I can invite users to join a site when I am online
- As a site Manager, I can archive or delete a site

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/153
- [ ] https://github.com/techmatters/terraso-product/issues/154
- [ ] https://github.com/techmatters/terraso-product/issues/155
- [ ] https://github.com/techmatters/terraso-product/issues/175
```

```[tasklist]
### Front end
- [ ] Screens for inviting people to a site
- [ ] Screens for managing roles of existing site members
- [ ] Screens for archiving a site
- [ ] Screens for deleting a site
- [ ] Screen for site config
```

```[tasklist]
### Back end
- [ ] Model data relationships for users managing sites
- [ ] Create GraphQL mutation to add user to a site
- [ ] Create GraphQL mutation to remove user from site
- [ ] Create GraphQL mutation to change user role in managing site
```

## Acceptance criteria

- After selecting a site, only site Managers should see a button to invite users.
  - Managers can add users as Viewers (default), Contributors, or Viewers
- All members of a site should be able to view a list of site members and their roles
- After someone has invited me to a site, I should see that site appear in the Sites list view
- After joining a site as a Manager, I should be able to invite other users to that project with specific permissions, or change the permissions of existing users.
  - Site contributors can edit site data inputs (i.e. slope, texture, etc.), photos, and notes, while site viewers can only see existing site data and reports.
- If I attempt to invite a user who does not have an account, I should see an error message 
- If I attempt to invite users while my device is offline, I should see an error message
- An anonymous user cannot invite other users to their sites, or be invited to join another site. 
- An anonymous user can only set their sites as private.
- If a site is transferred to a project, only the members of the project will be able to view the site after the transfer. 

[Site management spec](https://docs.google.com/document/d/1KxTegs-mJ_YTf1X5Fadmpb7TAW-rLB2SlBoDi8Y9sZk/edit?pli=1#heading=h.54w02ys7n8ko)

**Comment by ltseng** [comment] 2023-06-29 19:48
This user story is ready to work on from a design perspective, but functionality-wise, the data inputs and reports can come first.

**Comment by ltseng** [comment] 2023-07-28 19:53
@david-code @shrouxm @JeancarloBarrios will one of you create engineering issues for this?

**Comment by DerekCaelin** [comment] 2024-08-22 16:24
Closing as duplicate of component management tasks

**Closed as not planned by DerekCaelin** 2024-08-22 16:24 UTC
Labels: user story
